### ISSUE TITLE
Correções do Banco de dados

### ISSUE THREAD

**Issue by aocastro** [nattyFS/Salao-tcc#1]
Realizar a correções do banco de dados de acordo com a reunião do dia 22/03/2020.

![image](https://user-images.githubusercontent.com/56028189/112032834-924f9900-8b1b-11eb-8b7c-613db567eb28.png)

**Comment by nattyFS** [comment]
Banco:
![image](https://user-images.githubusercontent.com/61321090/112167549-4d853a00-8bcf-11eb-86f4-ddd6e7138f43.png)
 Hoje ainda faremos uma chamada com o professor de Banco De Dados para realizar uma análise completa
