### ISSUE TITLE
Estudo de Layout e proposta

### ISSUE THREAD

**Issue by aocastro** [nattyFS/Salao-tcc#2]
Realizar um estudo amplo sobre possibilidades de layput e cores para o projeto.

**Comment by leticianb** [comment]
Layout
![telahomecell](https://user-images.githubusercontent.com/61321107/112167056-f1221a80-8bce-11eb-9e47-e69fdc65afe4.jpg)
![telahomedesktop](https://user-images.githubusercontent.com/61321107/112167170-026b2700-8bcf-11eb-8aeb-b3c8afe51f9f.jpg)

**Comment by aocastro** [comment]
Proposta bem interessante.
